### ISSUE TITLE
[DisconnectClient] Bad behavior with local address

### ISSUE THREAD

**Issue by Bizarrus** [jchristn/WatsonWebsocket#41]
When you try to kick clients with `DisconnectClient`, you must add the `ip:port`-String from the client (for example `127.0.0.1:1234`).
But the server seems to transform `127.0.0.1` to `::1`:

![image](https://user-images.githubusercontent.com/1371300/98445537-8341ee80-2118-11eb-94d3-1e23ddf47ea6.png)
![image](https://user-images.githubusercontent.com/1371300/98445554-905edd80-2118-11eb-93f1-ac180ad5b5c8.png)

**StackTrace**

```
One or more errors occurred. (The received message type 'Text' is invalid after calling WebSocket.CloseAsync. WebSocket.CloseAsync should only be used if no more data is expected from the remote endpoint. Use 'WebSocket.CloseOutputAsync' instead to keep being able to receive data but close the output channel.)

at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
at System.Threading.Tasks.Task.Wait()
at WatsonWebsocket.WatsonWsServer.DisconnectClient(String ipPort)
at Launcher.Program.ClientConnected(Object sender, ClientConnectedEventArgs args)
at WatsonWebsocket.WatsonWsServer.<>c__DisplayClass47_1.<<AcceptConnections>b__1>d.MoveNext()"

```

**Comment by Bizarrus** [comment]
Okay, seems, that the NuGet-Package is outdated.

I've tried to use the Source in my project - Here, it works fine.

Can be closed, let it open as information to update the NuGet-Package.

**Comment by jchristn** [comment]
Thanks @Bizarrus
