### ISSUE TITLE
Websocket server suddenly interupted ( The remote party closed the Websocket connection without completing the closing handshake)

### ISSUE THREAD

**Issue by ange-black69** [jchristn/WatsonWebsocket#83]
Hello,
We are facing a issue on our Game WebSocket server.
After like 2 to 3 hours of activity the dotnet process stopped runing and thorwing that : The remote party closed the Websocket connection without completing the closing handshake.

Our code checks if they are connected before calling sendasync

Here is the stacktrace : 
`Mar 16 17:14:28 localhost dotnet[2843]: Unhandled exception. System.AggregateException: One or more errors occurred. (The remote party closed the WebSocket connection without completing the close handshake.)
Mar 16 17:14:28 localhost dotnet[2843]:  ---> System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
Mar 16 17:14:28 localhost dotnet[2843]:  ---> System.IO.IOException: Unable to write data to the transport connection: Broken pipe.
Mar 16 17:14:28 localhost dotnet[2843]:  ---> System.Net.Sockets.SocketException (32): Broken pipe
Mar 16 17:14:28 localhost dotnet[2843]:    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.CreateException(SocketError error, Boolean forAsyncThrow)
Mar 16 17:14:28 localhost dotnet[2843]:    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.SendAsyncForNetworkStream(Socket socket, CancellationToken cancellationToken)
Mar 16 17:14:28 localhost dotnet[2843]:    at System.Net.Sockets.Socket.SendAsyncForNetworkStream(ReadOnlyMemory`1 buffer, SocketFlags socketFlags, CancellationToken cancellationToken)
Mar 16 17:14:28 localhost dotnet[2843]:    at System.Net.Sockets.NetworkStream.WriteAsync(ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)
Mar 16 17:14:28 localhost dotnet[2843]:    at System.Net.WebSockets.ManagedWebSocket.SendFrameFallbackAsync(MessageOpcode opcode, Boolean endOfMessage, ReadOnlyMemory`1 payloadBuffer, CancellationToken cancellationToken)
Mar 16 17:14:28 localhost dotnet[2843]:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
Mar 16 17:14:28 localhost dotnet[2843]:    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
Mar 16 17:14:28 localhost dotnet[2843]:    at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
Mar 16 17:14:28 localhost dotnet[2843]:    at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
Mar 16 17:14:28 localhost dotnet[2843]:    at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
Mar 16 17:14:28 localhost dotnet[2843]:    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(Task`1 task, TResult result)
Mar 16 17:14:28 localhost dotnet[2843]:    at System.Threading.SemaphoreSlim.WaitUntilCountOrTimeoutAsync(TaskNode asyncWaiter, Int32 millisecondsTimeout, CancellationToken cancellationToken)
`

It happenend suddently.

Thanks you

**Comment by jchristn** [comment]
Hi @ange-black69 sorry for the delay!  Your stack trace doesn't show from which method in the library the exception is being thrown.  Could you help with that?  Thanks!
